### ISSUE TITLE
Permalinks for specific APIs

### ISSUE THREAD

**Issue by christianliebel** [GoogleChromeLabs/fugu-tracker#14]
**Is your feature request related to a problem? Please describe.**

I tried to link to a specific API from a blog post, but that doesn't seem to be possible at the moment.

**Describe the solution you'd like**

When opened with a permalink (e.g. https://fugu-tracker.web.app/#file-handling), the Fugu Tracker could
- scroll directly to the API
- open the API's card

When an API's card is opened, the URL in the address bar could be updated automatically. Alternatively, a new button could be introduced that navigates to the API's address or copies the URL to the clipboard. 

**Describe alternatives you've considered**

Path-based routing (without the hash fragment, as caniuse.com does it, e.g. https://caniuse.com/mdn-css_properties_content) would also be fine!

**Additional context**

<img width="1371" alt="Screenshot" src="https://user-images.githubusercontent.com/6698344/116964520-06996280-acac-11eb-902c-59abf01867bd.png">

**Comment by tomayac** [comment]
I have a half-started PR that does this. Assigning myself. No concrete ETA, though, due to a big upcoming Google event :-)

**Comment by tomayac** [comment]
@christianliebel See #23 that adds this.

**Comment by christianliebel** [comment]
@tomayac I believe the headings feature is broken, at least in the rolled out version:

![image](https://user-images.githubusercontent.com/6698344/122730744-dec18680-d27a-11eb-85d4-c59f4c903305.png)

**Comment by tomayac** [comment]
Oh, thanks. Fixed in https://github.com/GoogleChromeLabs/fugu-tracker/pull/26.
