### ISSUE TITLE
Section links

### ISSUE THREAD

**Issue by inexorabletash** [GoogleChromeLabs/fugu-tracker#16]
**Is your feature request related to a problem? Please describe.**
Ability to link directly to the OT, Started, Under Consideration, etc. sections. 

**Describe the solution you'd like**
Sections could have a "links" icon after the section name that allows easy copy/paste of the URL with #

**Comment by tomayac** [comment]
Will deal with this as part of https://github.com/GoogleChromeLabs/fugu-tracker/issues/14.

**Comment by tomayac** [comment]
@inexorabletash See #23 that adds this.

**Comment by Snugug** [comment]
Repoened as the PRs are being split
