### ISSUE TITLE
Shipped features showing in "Under Consideration"

### ISSUE THREAD

**Issue by inexorabletash** [GoogleChromeLabs/fugu-tracker#18]
**Describe the bug**

I noticed the following features are showing as Under Consideration, even though they've shipped:

* Web Bluetooth API
* WebUSB API

I'm not sure why they're showing up. Those were the only two I spotted, but there might be more.

**Comment by tomayac** [comment]
I believe this is because the relevant `M-\d+` labels were missing from the corresponding bugs. I have just added them and hope this fixes it.

**Comment by inexorabletash** [comment]
Thanks. And for posterity, it looks like you added the Proj-Fugu to those issues recently which is why it wasn't a problem before - they simply weren't listed, as they predated the Fugu effort.

**Comment by tomayac** [comment]
Exactly, this happened after [discussing this on Twitter](https://twitter.com/tomayac/status/1396006562162937856).
