### ISSUE TITLE
Daily Deploy workflow has been disabled

### ISSUE THREAD

**Issue by arayaryoma** [GoogleChromeLabs/fugu-tracker#28]
I often use this tool to see the status of Fugu APIs. Thank you for your development and maintenance.

**Describe the bug**
Daily Deploy workflow that is declared in https://github.com/GoogleChromeLabs/fugu-tracker/blob/main/.github/workflows/schedule.yml has been disabled because this repository doesn't have frequent activities.

**To Reproduce**

1. Go to https://github.com/GoogleChromeLabs/fugu-tracker/actions/workflows/schedule.yml
2. See the error message from GitHub

<img width="974" alt="
This scheduled workflow is disabled because there hasn't been activity in this repository for at least 60 days. Enable this workflow to resume scheduled runs. " src="https://user-images.githubusercontent.com/5627119/139925745-04ac9e45-0eaa-4790-b32f-c2525e7ea9cb.png">

**Expected behavior**
Daily Deploy workflow should be triggered as we expectected.

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by Snugug** [comment]
Oh! I see! I've just re-enabled it. Let's see if it redeploys EOD today

**Comment by arayaryoma** [comment]
Daily Deploy looks to have been restarted by an event that was triggered by [this commit](https://github.com/GoogleChromeLabs/fugu-tracker/commit/682974bc1e4c38c5116a2a6bf52f366c93e04281)! Thanks for responding!
