### ISSUE TITLE
Open bug appears in "Shipped" section

### ISSUE THREAD

**Issue by tomayac** [GoogleChromeLabs/fugu-tracker#30]
See https://fugu-tracker.web.app/#:~:text=Introduce%20api%20for%20standardized%20database%20access, which appears in the "Shipped" section, but its bug https://crbug.com/1250207 is not fixed.

**Comment by inexorabletash** [comment]
The logic is probably that the bug has label "M-95" which is "in the past".

Updating the heuristic to do something sensible when there's a mismatch (but still open but date has passed) would be good.

I'll update the bug to drop that milestone, so it'll probably disappear from the dashboard.

**Comment by tomayac** [comment]
Fixed for now.
