### ISSUE TITLE
Issue 1136480: FUGU Implement capture of system and application audio output to headphones and speakers

### ISSUE THREAD

**Issue by guest271314** [GoogleChromeLabs/fugu-tracker#34]
**Is your feature request related to a problem? Please describe.**
No specified way to capture `window.speechSynthesis.speak()`, specific application audio output, or entire system audio output.

**Describe the solution you'd like**
Ability to capture audio output from `window.speechSynthesis.speak()`, specific application audio output, or entire system audio output.

**Describe alternatives you've considered**
Native Messaging.

**Additional context**
- https://bugs.chromium.org/p/chromium/issues/detail?id=1136480
- https://github.com/WebAudio/web-audio-api/issues/2478

**Comment by tomayac** [comment]
Closing according to https://bugs.chromium.org/p/chromium/issues/detail?id=1136480#c13.
