### ISSUE TITLE
Indicator for IWA-only APIs

### ISSUE THREAD

**Issue by inexorabletash** [GoogleChromeLabs/fugu-tracker#35]
A handful of Proj-Fugu features are currently in progress but only expected to ship in Isolated Web Apps. It would be nice to highlight these somehow so it's clear that these are not targeting the open web. Some are currently in the Fugu tracker, others aren't.

* [Smart Cards](https://chromestatus.com/feature/6411735804674048) - no crbug
* [Direct Sockets](https://chromestatus.com/feature/6398297361088512) - [crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=909927) - not marked Proj-Fugu
* Borderless [crbug](https://bugs.chromium.org/p/chromium/issues/detail?id=1235285) - marked Proj-Fugu

Maybe just "IWA" as a monorail label, and we show ... some variant of the PWA logo that says IWA instead?

![iwalogo](https://user-images.githubusercontent.com/771547/191623949-945e22ba-1fcb-4e1e-a9a1-51286545de7b.svg)

**Comment by tomayac** [comment]
Provocative question: Should IWA features even be listed on the _Fugu_ tracker? Removing the `proj-fugu` label would be the no-code approach. I guess this would then spark the "Do we need an IWA tracker?" question. Do we?

**Comment by inexorabletash** [comment]
@reillyeon for opinions.

One reason to keep them on the tracker is visibility - "we ack the feature request, but aren't planning to expose it to the web". That could be handled in a different way, e.g. we make two bugs, one tracking IWA exposed implementation, another as a feature request to figure out how to expose it to the web.

Definitely curious for thoughts on what we should do here.

**Comment by tomayac** [comment]
For feasibility, it could definitely be done with a label, similar to the PWA label in https://github.com/GoogleChromeLabs/fugu-tracker/blob/70dbff23d98b96746d1dd6fa6f54c7563608ea91/templates/includes/card.html#L18.

**Comment by reillyeon** [comment]
We should be tracking them somewhere. For better or worse "Fugu" is the brand for adding powerful capabilities to "the web" and so people are going to be coming here to find out about new capabilities for the web and web-like platforms.

+1 to the proposal to add an IWA-only label to the Fugu tracker.

**Comment by tomayac** [comment]
Fair game. I'll assign this to me and will see what I can do.
