### ISSUE TITLE
Adding "Report a problem" link to the page

### ISSUE THREAD

**Issue by hoch** [GoogleChromeLabs/fugu-tracker#4]
Love the tracker, but it would be great if one can report a problem when they see inaccurate information.

**Comment by tomayac** [comment]
@Snugug You might want to look into http://go/feedback-web/api.

**Comment by Snugug** [comment]
This seems like a good enhancement. A question I have on the implementation: would this be per-API or for the site as a whole? Are you envisioning feedback being fed to here (GitHub issues) or to one of the existing sources of data (Chrome Status/CRBug/Origin Trails)?

**Comment by inexorabletash** [comment]
There's probably at least three sources of feedback that visitors may be interested in providing; we should make sure it's clear which they're trying to give and ensure the UI helps them route it appropriately:

* Feedback on Fugu overall - "I want a new browser capability!"
  * link to file an issue at the bottom of https://web.dev/fugu-status/
* Feedback on a specific capability on the tracker
  * link to explainer repo or crbug? maybe chromestatus should have a "where to give feedback" URL field?
* Feedback on the tracker itself 
  * i.e. https://github.com/GoogleChromeLabs/fugu-tracker/issues

i.e. a "Feedback? click here" link will probably end up with a mix of all three, so we should make the link(s) more nuanced.

Examples that have come up so far also include e.g. "the date on API Foo seems wrong - how do I fix it?" which is almost a mix of the latter two. Maybe that's a special case we should highlight?
