### ISSUE TITLE
Recent Fugu Requests from the bug tracker not showing up

### ISSUE THREAD

**Issue by orbitlens** [GoogleChromeLabs/fugu-tracker#40]
**Describe the bug**
Some time ago I submitted a [feature request](https://bugs.chromium.org/p/chromium/issues/detail?id=1371645) following Fugu guidelines, but I don't see it on https://fugu-tracker.web.app. The same goes for other recent feature requests. New ideas may fall into oblivion if they don't receive enough attention, and showing them here seems like a crucial first step for this.

Are there some special criteria of displaying requests on the fugu-tracker website I'm not aware of?

**Comment by tomayac** [comment]
Your feature request was missing the `proj-fugu` label for some reason. I have added it and the tracker should catch your bug upon the next deploy. Thanks for reporting!

**Comment by tomayac** [comment]
And it's there: https://fugu-tracker.web.app/#fugu-request:-in-memory-storage-for-service-workers-in-pwa. Thanks for the report again.
