### ISSUE TITLE
Fugu API Tracker is broken: Downloading Fugu bugs from https://bugs.chromium.org does not work anymore

### ISSUE THREAD

**Issue by beaufortfrancois** [GoogleChromeLabs/fugu-tracker#47]
@tomayac As you may have seen with https://github.com/GoogleChromeLabs/fugu-tracker/actions/runs/7777777943, https://fugu-tracker.web.app/ is not updated anymore due to chromium issue tracker migration (https://developer.chrome.com/blog/chromium-issue-tracker-migration-2024?hl=en).

Shall we try to address this issue?
Find a new endpoint?

**Comment by tomayac** [comment]
If it's really just a matter of finding the new endpoint, we should probably address this. I didn't closely follow the migration; did you?

**Comment by beaufortfrancois** [comment]
I had a quick look this morning and it seems like our fugu-tracker scraper relies on the following rprc endpoint from the old chromium tracker to get all crbugs data:

https://github.com/GoogleChromeLabs/fugu-tracker/blob/456670240e20486b9430459a6c71f7e787bc68d2/data/bugs.js#L144

@jcgregorio Do you if there's a way in the new Chromium tracker to access this kind of data?

**Comment by jcgregorio** [comment]
Please file an issue here:
https://issues.chromium.org/issues/new?component=1506133&template=1933541

That will get the right folks looking into it.

   Thanks,
   -joe

**Comment by beaufortfrancois** [comment]
Thank you @jcgregorio 
I just filed https://g-issues.chromium.org/issues/324057537

**Comment by beaufortfrancois** [comment]
Status update: We're still investigating how to proceed.

**Comment by beaufortfrancois** [comment]
Here's the current plan: Redirect https://fugu-tracker.web.app to either:
- https://chromestatus.com/newfeatures?q=tags%253D%2522fugu%2522 if we're able to update the "search tags" of all the chrome status fugu entries
- or https://issues.chromium.org/issues?q=customfield1223031:proj-fugu%20-customfield1223031:proj-fugu-efforts%20-is:obsolete

None of those is perfect replacement but it sounds like a more maintainable way to address this issue.

**Comment by libreom** [comment]
A more complete solution is needed

**Comment by beaufortfrancois** [comment]
I realize this isn't ideal, but it's the best we can do right now with the limitations we have.

See https://github.com/GoogleChromeLabs/fugu-tracker/pull/50
