### ISSUE TITLE
Is the website broken?

### ISSUE THREAD

**Issue by simevidas** [GoogleChromeLabs/fugu-tracker#48]
Sorry if this is a stupid question. I’m trying to view the content on the website, but there is nothing there. I tried in Chrome on macOS. See the attached video. Shouldn’t there be a big table that lists all the Fugu APIs or something like that?

https://github.com/GoogleChromeLabs/fugu-tracker/assets/716405/b11bed93-7c08-469e-ad37-50d5456a3978

**Comment by tomayac** [comment]
Yes, the root cause is https://github.com/GoogleChromeLabs/fugu-tracker/issues/47.
