### ISSUE TITLE
The fugu tracker seems to be broken

### ISSUE THREAD

**Issue by nickchomey** [GoogleChromeLabs/fugu-tracker#49]
![image](https://github.com/GoogleChromeLabs/fugu-tracker/assets/88559987/6277f3e7-003d-47d2-a67a-32f4485721b0)

I see nothing, on multiple browsers.

**Comment by tomayac** [comment]
Yes. This is https://github.com/GoogleChromeLabs/fugu-tracker/issues/47. Sorry.
