### ISSUE TITLE
Consider adding a quick link via URL hash

### ISSUE THREAD

**Issue by hoch** [GoogleChromeLabs/fugu-tracker#7]
It would be more convenient to point someone directly to an API entry in the tracker, if it supports the hash routing:

https://fugu-tracker.web.app/#web-codecs

Currently, I am asking developers to go to the tracker and search the keyword instead.

**Comment by tomayac** [comment]
+1. As an interim solution you could also use [text fragment URLs](https://web.dev/text-fragments/).

**Comment by hoch** [comment]
Could you provide an example of "WebCodecs" with the text fragment URL? I tried below, but had no luck:
https://fugu-tracker.web.app/#:~:text=Web%20Codecs

**Comment by tomayac** [comment]
They spell it WebCodecs (no space), so the correct link is https://fugu-tracker.web.app/#:~:text=WebCodecs.

**Comment by Snugug** [comment]
In theory, the bug search should work for this (https://fugu-tracker.web.app/?version=0&search=&platforms=%5B%5D&bug=897297) but it seems as if filtering by bug is currently broken. I think I'd prefer to fix that bug than add clean-name hashing as the names are likely to change over time. Does that work as a solution?

**Comment by hoch** [comment]
I felt it's always easy to throw a single link when I talk to developers. I think @tomayac's solution works fine, but we'll have to remember to use `#~:=:text=`. That said, I am fine with having a complete search feature. Thanks for the consideration! :)
