### ISSUE TITLE
The Fugu tracker should be labeled generically to represent all Chromium browsers

### ISSUE THREAD

**Issue by thejohnjansen** [GoogleChromeLabs/fugu-tracker#8]
**Describe the bug**
Currently the fugu tracker says "Chrome 88" "Chrome 89" and "Chrome 90"

**Expected behavior**
It should say "Chromium" I think. Particularly because these features are available in Edge and several of them are actually being developed at Microsoft.

**Comment by thejohnjansen** [comment]
@Snugug , Is there a delay after the changes merge before they show up on the site? I'm still seeing Chrome in the headings...
![image](https://user-images.githubusercontent.com/2119039/113736222-c2697100-96b1-11eb-9b77-3eb954cce45d.png)

**Comment by Snugug** [comment]
Yah. We deploy 1/day, usually around 8:00pm Eastern.

**Comment by thejohnjansen** [comment]
Awesome. Thanks so much for making this change.
